config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "businesses#index"

  resources :users do
    resources :businesses
  end

  resources :businesses do
    resources :invoices
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/business.rb
class Business < ApplicationRecord
  belongs_to :user
  has_many :invoices
end

app/models/invoice.rb
class Invoice < ApplicationRecord

  belongs_to :business

  def send_confirmation
    if check_paid
      send_email
    else
      flash[:error] = "error"
    end
  end

  private

  def check_paid
    return True unless !@invoice.paid
  end

  def send_email
    # function for sending email
  end


end


# bootstrap

app/models/user.rb
class User < ApplicationRecord

  has_many :businesses, class_name: "Business", foreign_key: "user_id"
  has_many :invoices
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/businesses_controller.rb
class BusinessesController < ApplicationController

  def index
    if current_user.admin
      @businesses = Business.all
    else
      @businesses = current_user.businesses
    end
  end

  def new
    @business = Business.new
  end

  def create
    build_biz
    save_biz or render :new
  end

  def show
    @user = current_user
    @business = Business.find_by(id: params[:id])
  end

  def destroy
  end

  private

    def biz_params
      biz_params = params[:business]
      biz_params ? biz_params.permit(:name, :website, :biz_type, :email): {}
    end

    def build_biz
      @biz ||= biz_scope.build
      @biz.attributes = biz_params
    end
    
    def save_biz
      if @biz.save
        redirect_to @biz
      end
    end

    def biz_scope
      current_user.businesses
    end
end

app/controllers/invoices_controller.rb
class InvoicesController < ApplicationController
  before_action :current_biz
  skip_before_action :verify_authenticity_token

  def index
    if !current_user
      redirect_to new_user_session_path
    else
      @invoices = current_user.businesses.invoices
    end
  end

  def show
    @invoice ||= Invoice.find(params[:id])
  end

  def new
    build_invoice 
  end

  def create
    build_invoice
    save_invoice or render :new
  end

  private
    
    def current_biz
      @biz = Business.find_by(id: params[:business_id])
    end

    def invoice_params
      invoice_params = params[:invoice]
      invoice_params ? invoice_params.permit(:title, :services, :payer_name, :payer_email, :paid, :price, :business_id) : {}
    end

    def build_invoice
      @invoice ||= invoice_scope.build
      @invoice.attributes = invoice_params
    end
    
    def save_invoice
      if @invoice.save
        redirect_to business_invoice_path(@biz, @invoice)
      end
    end

    def invoice_scope
      @biz.invoices
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/invoices_helper.rb
module InvoicesHelper
end

app/views/businesses/new.html.erb
<%= form_for @business do |f| %>
  <%= f.text_field :biz_name, required: true %>
  <%= f.text_field :biz_email, required: true %>
  <%= f.text_field :biz_website, required: false %>
  <%= f.text_field :biz_type, required: true %>
  <%= f.submit %>
<% end %>

app/views/businesses/show.html.erb
<%= @business.name %>
<%= link_to 'Create Invoice', new_business_invoice_path(@business) %>

app/views/invoices/index.html.erb
<table class="table table-dark">
  <thead>
    <tr>
      <th scope="col">Title</th>
      <th>Paid</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <% if @invoices %>
        <% @invoices.each do |invoice| %>
        <tr>
          <td><%= link_to invoice.title, user_invoice_path(current_user, invoice.id), class: "td-link" %></td>
          <td><%= invoice.paid.to_s.capitalize %></td>
        </tr>
        <% end %>
      <% else %>
        no invoices bitch
      <% end %>
    </tr>
  </tbody>
</table>


<!-- le puse un style todo animal pq esta vaina no agarraba los estilos y queria ver como se veia, ya lo arreglo -->
<style media="screen">

.table-dark {
  width: 70%;
  margin: auto;
  margin-top: 10vh;
}

.td-link {
  color: #fff;
}

.td-link:hover {
  color: #dff9fb;
  text-decoration: line-through;
}

@media(max-width: 400px){
  .table-dark {
    width: 85%;
    margin: auto;
    margin-top: 5vh;
  }
}
</style>

app/views/invoices/new.html.erb
<div class="w-50 m-auto">
  <button onClick='addServices()'>Add Services</button>
  <%= form_for [@biz, @invoice] do |f| %>

  <div class='form-group'>
    <%= f.label :title %>
    <%= f.text_field :title, class: 'form-control' %>
  </div>
  <div class='row services-row'>
    <div class='col-8'>    
      <%= f.label :services %>
      <%= f.text_field :services, class: 'form-control' %>
    </div>
    <div class='col-4'>    
      <%= f.label :price %>
      <%= f.number_field :price, class: 'form-control service-price', onblur: 'addValues()', value: 0 %>
    </div>
    
 </div>
  <div class='form-group'>
    <%= f.label :payer_name %>
    <%= f.text_field :payer_name, class: 'form-control' %>
  </div>
  <div class='form-group'>
    <%= f.label :payer_email %>
    <%= f.text_field :payer_email, class: 'form-control' %>
  </div>
  <div class="form-check">
    <%= f.check_box :paid, { class: 'form-check-input' } %>
    <%= f.label :paid %>
  </div>
  <div class='row'>
    Total: 
    <span class='total'>
    </span>
  </div>

  <%= f.submit class: 'btn btn-primary' %>
  <% end %>
</div>

  <script>
    
    function addValues(){
      let value = [...document.querySelectorAll('.service-price')].map(i => i.value).reduce((accumulator, currentValue) => parseFloat(accumulator) + parseFloat(currentValue))
      document.querySelector('.total').innerText = value
    }

function addServices() {
  let priceField = document.createElement('input')
  priceField.type = 'number'
  priceField.setAttribute('class', 'form-control service-price')
  priceField.value = 0
  priceField.onblur = addValues

  let priceLabel = document.createElement('label')
  priceLabel.htmlFor = 'invoice_price'
  priceLabel.innerText = 'Price'

  let col4 = document.createElement('div')
  col4.setAttribute('class', 'col-4')

  col4.appendChild(priceLabel) 
  col4.appendChild(priceField) 

  let serviceField = document.createElement('input')
  serviceField.type = 'text'
  serviceField.setAttribute('class', 'form-control')

  let serviceLabel = document.createElement('label')
  serviceLabel.htmlFor = 'invoice_services'
  serviceLabel.innerText = 'Services'

  let col8 = document.createElement('div')
  col8.setAttribute('class', 'col-8')

  col8.appendChild(serviceLabel) 
  col8.appendChild(serviceField) 

  document.querySelector('.services-row').appendChild(col8)
  document.querySelector('.services-row').appendChild(col4)
}
  
  </script>

app/views/invoices/show.html.erb
<ul class="list-group w-50 m-auto">
  <li class="list-group-item">Title: <%= @invoice.title %></li>
  <li class="list-group-item">Services: <%= @invoice.services %></li>
  <li class="list-group-item">Client: <%= @invoice.payer_name %></li>
  <li class="list-group-item">Email: <%= @invoice.payer_email %></li>
  <li class="list-group-item">Paid: <%= @invoice.paid %></li>
  <li class="list-group-item">Price: <%= @invoice.price %></li>
</ul>

app/views/layouts/_footer.html.erb
<footer id="footer">
  <p class="footer-text">
    Website built by <a href="https://www.jmdevshop.com" target="_blank" rel="noreferrer noopener" class="jmdev">JM Dev</a>
  </p>

  <p class="footer-text">
    Donate BTC: 13A8GMJs11D9Eak1upFSRCpsnjjyG5PN1F
  </p>
  <p class="footer-text">
    Donate ETH: 0x1b20cc4937e761625C56006040e711C27161CBD3
  </p>
</footer>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="/">Navbar</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="/">Home <span class="sr-only">(current)</span></a>
      </li>
      <% if current_user %>
        <li class="nav-item">
          <%= link_to 'Create a Business', new_user_business_path(current_user), class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to 'Check your Businesses', user_businesses_path(current_user), class: "nav-link" %>
        </li>
        <li class="nav-item">
        </li>
        <li class="nav-item">
          <%= link_to 'Logout', destroy_user_session_path, method: :delete, class: "nav-link" %>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to 'Login', new_user_session_path, class:"nav-link" %>
        </li>
      <% end %>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Dropdown
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <a class="dropdown-item" href="#">Action</a>
          <a class="dropdown-item" href="#">Another action</a>
          <div class="dropdown-divider"></div>
          <a class="dropdown-item" href="#">Something else here</a>
        </div>
      </li>
    </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>InvoiceDemo</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
  </head>
  <%= render 'layouts/header.html.erb' %>
  <body>
    <%= yield %>
  </body>

  <%= render 'layouts/footer.html.erb' %>

</html>